server:
  port: 8082

spring:
  application:
    name: data-service
  datasource:
    url: jdbc:mysql://localhost:3306/dlabrna_data?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848